# List of figures {-}

| Figure name | Figure number |
| :-----------|:-------------:|
| Energy consumption for electricity generation from 2017–2021 | \@ref(fig:fig-fuelelygen2017-2021) |
| EGAT electricity sale profile to MEA in 2019 | \@ref(fig:EGAT-sale-to-MEA-2019) |
| EGAT electricity sale profile to PEA-R1 in 2019 | \@ref(fig:EGAT-sale-to-PEA-R1-2019) |
| EGAT electricity sale profile to PEA-R2 in 2019 | \@ref(fig:EGAT-sale-to-PEA-R2-2019) |
| EGAT electricity sale profile to PEA-R3 in 2019 | \@ref(fig:EGAT-sale-to-PEA-R3-2019) |
| EGAT electricity sale profile to PEA-R4 in 2019 | \@ref(fig:EGAT-sale-to-PEA-R4-2019) |
| EGAT electricity sale profile to PEA (all regions) in 2019 | \@ref(fig:EGAT-sale-to-PEA-allregion-2019) |
| EGAT electricity sale profile to direct customer in PEA-R1 in 2019 | \@ref(fig:EGAT-sale-to-DCR1-2019) |
| EGAT electricity sale profile to direct customer in PEA-R2 in 2019 | \@ref(fig:EGAT-sale-to-DCR2-2019) |
| EGAT electricity sale profile to direct customer in PEA-R3 in 2019 | \@ref(fig:EGAT-sale-to-DCR3-2019) |
| EGAT electricity sale profile to direct customer in PEA-R4 in 2019 | \@ref(fig:EGAT-sale-to-DCR4-2019) |
| EGAT electricity sale profile to direct customer in PEA (all regions) in 2019 | \@ref(fig:EGAT-sale-to-DCALLREG-2019)|
| EGAT electricity sale profile to PEA R1 and direct customer in PEA R1 in 2019 | \@ref(fig:EGAT-sale-to-pear1-dcr1-2019) |
| EGAT electricity sale profile to PEA R2 and direct customer in PEA R2 in 2019 | \@ref(fig:EGAT-sale-to-pear2-dcr2-2019) |
| EGAT electricity sale profile to PEA R3 and direct customer in PEA R3 in 2019 | \@ref(fig:EGAT-sale-to-pear3-dcr3-2019) |
| EGAT electricity sale profile to PEA R4 and direct customer in PEA R4 in 2019 | \@ref(fig:EGAT-sale-to-pear4-dcr4-2019) |
| EGAT electricity sale profile 2019 | \@ref(fig:EGAT-sale-2019) |
| MEA electricity requirement profile in 2019 | \@ref(fig:MEA-REQ-2019) |
| The electricity requirement profile from PEA R1 in 2019 | \@ref(fig:PEAR1-REQ-2019) |
| The electricity requirement profile from PEA R2 in 2019 | \@ref(fig:PEAR2-REQ-2019) |
| The electricity requirement profile from PEA R3 in 2019 | \@ref(fig:PEAR3-REQ-2019) |
| The electricity requirement profile from PEA R4 in 2019 | \@ref(fig:PEAR4-REQ-2019) |
| The electricity requirement profile from TNB in 2019 | \@ref(fig:TNB-REQ-2019) |
| The electricity requirement profile from EDL in 2019 | \@ref(fig:EDL-REQ-2019) |
| The electricity requirement profile from PEA R2 and EDL in 2019 | \@ref(fig:R2EDL-REQ-2019) |
| The electricity requirement profile from PEA R3 and TNB in 2019 | \@ref(fig:R3TNB-REQ-2019) |
| The electricity requirement profile from MEA and PEA R1 in 2019 | \@ref(fig:MEAPEAR1-REQ-2019) |
| The EGAT net generation profile in 2019 | \@ref(fig:EGT-NGN-2019) |
| Transmission loss profile in 2019 | \@ref(fig:TRTLOSS-2019) |
| The MEA transmission loss and use profile in 2019 | \@ref(fig:MEATRTLOSS-2019) |
| The PEA R1 transmission loss and use profile in 2019 | \@ref(fig:PEAR1TRTLOSS-2019) |
| The PEA R2 transmission loss and use profile in 2019 | \@ref(fig:PEAR2TRTLOSS-2019) |
| The PEA R3 transmission loss and use profile in 2019 | \@ref(fig:PEAR3TRTLOSS-2019) |
| The PEA R4 transmission loss and use profile in 2019 | \@ref(fig:PEAR4TRTLOSS-2019) |
| The MEA total net electricity generation requirement in 2019 | \@ref(fig:MEA-TOTNETGEN-2019) |
| The PEA R1 total net electricity generation requirement in 2019 | \@ref(fig:PEAR1-TOTNETGEN-2019) |
| The PEA R2 total net electricity generation requirement in 2019 | \@ref(fig:PEAR2-TOTNETGEN-2019) |
| The PEA R3 total net electricity generation requirement in 2019 | \@ref(fig:PEAR3-TOTNETGEN-2019) |
| The PEA R4 total net electricity generation requirement in 2019 | \@ref(fig:PEAR4-TOTNETGEN-2019) |
| Total net electricity generation requirement in 2019 | \@ref(fig:TOTNETGEN-2019) |
| Electricity generation from VSPP in MEA region during 2005–2021 | \@ref(fig:vsppene-2005-2021) |
| Electricity generation from VSPP in PEA region during 2005–2021 | \@ref(fig:plot-peavspp-ene-2005-2021) |
| Electricity generation from DEDE in PEA region during 2005–2021 | \@ref(fig:plot-peadede-ene-2005-2021) |
| Self electricity generation in PEA region during 2005–2021 |\@ref(fig:plot-peasfgen-ene-2005-2021)|
| Electricity generation from VSPP during 2015–2021 |\@ref(fig:plot-totvspp-ene-2015-2021)|
| VSPP contract capacity in the PDP2018 Rev.1 | \@ref(fig:plot-vsppConCapPDP2018r1)|
| VSPP electricity generation in the PDP2018 Rev.1 | \@ref(fig:plot-vsppEnePDP2018r1)|
| VSPP contract capacity in the PDP2022 case 7 | \@ref(fig:plot-vsppcontractcapPDP2022C7) |
| VSPP electricity generation in the PDP2022 case 7 | \@ref(fig:plot-vsppenergyPDP2022C7) |
| Total electricity generation from VSPPs in PDP2018 Rev.1 | \@ref(fig:plot-merge-vspp-ext-pdp) |
| Total electricity generation from VSPPs in PDP2022 case 7 | \@ref(fig:plot-merge-vspp-ext-pdp2023c7) |
| VSPPs contract capacity | \@ref(fig:plot-comparecontractvsppPDP2018r1-PDP2022c7)|
| VSPPs contract capacity mix | \@ref(fig:plot-comparecontractfuelvsppPDP2018r1-PDP2022c7)|
| Electricity generation from VSPPs | \@ref(fig:plot-comparevsppPDP2018r1-PDP2022c7)|
| Electricity generation mix from VSPPs | \@ref(fig:plot-comparefuelvsppPDP2018r1-PDP2022c7)|
| Electricity consumption in EGAT head office and others | \@ref(fig:plot-useandoffice)|
| Electricity consumption in EGAT substations | \@ref(fig:plot-useegatsub) |
| Electricity consumption in station service (off-load) | \@ref(fig:plot-usestatserv) |
| Electricity consumption in Mae Moh mining | \@ref(fig:plot-usemaemoh) |
| Electricity consumption by pumped storage hydropower plants | \@ref(fig:plot-usepump)|
| Total EGAT internal electricity consumption | \@ref(fig:plot-totalusepump) |
| Total EGAT electricity consumption by categories | \@ref(fig:plot-facettotalusepump) |
| Transmission loss in EGAT power system | \@ref(fig:plot-translosspercent) |
| Purchased electricity by EGAT direct customers | \@ref(fig:plot-directCustomer)|
| Purchased electricity by domestic customers | \@ref(fig:plot-dcdomestic) |
| Purchased electricity by neighboring customers | \@ref(fig:plot-dcneighboring) |