---
title: "Electricity profiles"
author: "Puttipong Chunark, Ph.D."
date: "Last compile on `r format(Sys.time(), '%d %B, %Y'); Sys.time()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
# bibliography:
description: |
  This webpage is created to understand the electricity load profile at all 
  levels. R coding techniques are included. Readers can learn how to code 
  the R language in the format of scripts, R markdown, and bookdown.
link-citations: yes
github-repo: "PChunark/load_forecast_EGAT_strategies"
---


# About {-}

This webpage is created to understand the electricity load profile at all 
levels. R coding techniques are included. Readers can learn how to code 
the R language in the format of scripts, R markdown, and bookdown.

<!--chapter:end:index.Rmd-->

# Introduction

Electricity is one of the key final energy to drive an economy. It is used to provide enduse demands. For instance, charging electric vehicles (EVs), lighting houses, heating water and cooking, driving motors to convey products in industrial processes.

In 2021, an electricity consumption was 201

<!--chapter:end:code_markdown/01-intro.Rmd-->

# Electricity profiles

This chapter provides electricity profiles and a R coding technique. 
Electricity profiles are illustrated to give an insight into profile behavior. 
R coding technique are given in order to understand the process flow and 
manage the big data obtained from several sources in the organization.


## Pre-requisite software


<!--chapter:end:code_markdown/02-elyprofile.Rmd-->

